import { useState, useEffect } from "react";
import Head from "next/head";

import BlogList from "@/components/blog/BlogList";
import SearchUser from "@/components/user/SearchUser";
import BlogModal from "@/components/blog/BlogModal";


export default function Home({ posts, comments }) {
  const [modalState, setModal] = useState(false);
  const [content, setContent] = useState();
  const [comment, setComment] = useState(comments);
  useEffect(() => {
    setComment(comments.filter((list) => list.post_id == content?.id));
  }, [content]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <div className="h-screen w-[80%]">
          {posts.map((list) => (
            <div className="pt-4 px-[10%] " key={list.id}>
              <BlogList
                post={list}
                setState={setModal}
                setContent={setContent}
                setComment={setComment}
              />
            </div>
          ))}
        </div>
        <div className="fixed top-[20%] right-[0] w-[20%]">
          <SearchUser />
        </div>
        <div
          className={
            "fixed inset-[0] " +
            (modalState == true ? " " : " pointer-events-none")
          }
        >
          <BlogModal
            state={modalState}
            setState={setModal}
            content={content}
            comment={comment}
          />
        </div>
      </div>
    </>
  );
}

export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const resPosts = await fetch("https://gorest.co.in/public/v2/posts");
  const posts = await resPosts.json();

  const resComments = await fetch("https://gorest.co.in/public/v2/comments");
  const comments = await resComments.json();
  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
      comments,
    },
  };
}
